### PR TITLE
Upgrade infrastructure to support Node 10

### PR DESCRIPTION
**Pull request by DaniilShmelev**
**Changes**: basically replicated these PRs ([first](https://github.com/microsoft/azure-pipelines-tasks/pull/13525), [second](https://github.com/microsoft/azure-pipelines-tasks/pull/13796))
- allow tasks to choose their TS version
- allow tests to run on both node6 and node10
- update dependencies (@types/node, @types/mocha, sync-request)
- **rename all task's folders to use CamelCase**

Why the last change was made: before we had to use
`node make.js build --task app-store-release` for building, but
`node make.js test --task AppStoreRelease` for testing (uses task name from task.json)
This is inconsistent with the azure-pipelines-tasks repo, so I renamed all folders using CamelCase and also included [this change](https://github.com/microsoft/azure-pipelines-tasks/pull/7040/files#diff-53c70f37847db86d5ef8f8ed103140aebe630332facb6af5cd99e4845c180ef8L129) to prevent future issues with different folder and task names. Now the behavior is more consistent:
`node make.js build --task AppStoreRelease`
`node make.js test --task AppStoreRelease`

**Documentation changes required:** No

**Added unit tests:** No

**Attached related issue:** https://github.com/microsoft/build-task-team/issues/676

### CODE REVIEW

**Comment by anatolybolshakov** [comment]
Could it make more sense to make it consistent with in-the-box tasks - so it will always use names in format 'AppStoreRelease'?

**Comment by DaniilShmelev** [comment]
> Could it make more sense to make it consistent with in-the-box tasks - so it will always use names in format 'AppStoreRelease'?

Yeah, I think it would be good if we used CamelCase everywhere

**Comment by anatolybolshakov** [comment]
Since we rename tasks - could you check that it works fine when previous task already exists on agent?

**Review by egor-bryzgalov — COMMENTED** [review]
We should update `make-options.json` file and ensure gulp commands work fine.

**Comment by DaniilShmelev** [comment]
Checked:
- [x] `node make.js build/test` commands
- [x] `gulp ...` commands
- [x] tsc version installation
- [x] node version installation
- [x] test execution handler (node 6 / node 10)

**Review by egor-bryzgalov — APPROVED** [review]

**Comment by anatolybolshakov** [comment]
Please test on prem - if it installs properly and substitutes previous version (since there was renaming)

**Review by anatolybolshakov — APPROVED** [review]

**Comment by egor-bryzgalov** [comment]
Tested:
✔️ gulp build
✔️ gulp test
✔️ gulp prod
✔️ gulp packageprod
✔️ Installing to the latest on-premise AzDO server as an update to pre-installed extension from the marketplace.

**Pull request merged**
